### ISSUE TITLE
Uncaught Syntax Error

### ISSUE THREAD

**Issue by rw215** [Regis011/wp-child-theme#1]
Not sure if this is even a true issue. I set this up in my project and it works great! Awesome work. 

The one issue I saw in my console was this message

custom.js:72 Uncaught TypeError: Cannot read property 'querySelector' of null
    at custom.js:72
    at custom.js:139
(anonymous) @ custom.js:72
(anonymous) @ custom.js:139

Just wondering if this is anything to worry about, and if / how I should go bout fixing it?

**Comment by Regis011** [comment]
I have updated that child themes so you will not get more the same mistake. Make one git pull or update /js/src/custom.js. 
Otherwise, it's not that big stuff but I like the console to be without this.

**Comment by rw215** [comment]
Aw thanks man! I wasn't even sure if it was a real issue. I am using this within an OceanWP Child theme. I really appreciate it.
